### ISSUE TITLE
epoch_300_fusion_base.pth

### ISSUE THREAD

**Issue by ymy23** [MedAI-Vision/CMR-AI#3]
Hello, thanks for your great work. I have a question about the config part. How can I generate epoch_300_fusion_base.pth? It seems that there is no code in this repository.

**Comment by PRMA-PRMA** [comment]
I see you marked this as complete - did you figure out where to get the pretrained weights for each view?

**Comment by ymy23** [comment]
> 我看到您将其标记为完成 - 您是否想出从哪里获取每个视图的预训练权重？

I use swin_base_patch244_window877_kinetics600_22k.pth as the pretrained weights.
